from snakemake.utils import min_version
min_version("6.0")

configfile: "config/config.yaml"

module polymap:
    # here, plain paths, URLs and the special markers for code hosting providers (see below) are possible
    snakefile: "../../../polymap/workflow/Snakefile" # this is dangerous.. what if move? better to use github path...

use rule * from polymap as polymap_*

